// Orphaned indexes: card-catalog indexes that no current collection writes.
// card-catalog never deletes files, so these stay until someone removes
// them, and an orphan can keep exposing a collection that has since become
// ignored (ADR-0002).

import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { isFile, joinRel, relBasename } from "./paths.ts";
import type { Repo } from "./repo.ts";

const MARKERS = ["Generated by the card-catalog plugin", "Generated by the adr-index plugin"];
const SKIP_DIRS = new Set(["node_modules", "dist", "build", "target", "vendor"]);
const MAX_DEPTH = 8;

/**
 * Repo-relative paths of orphaned indexes, outside ignored paths. With
 * `allMarkdown`, every markdown file is checked (validate); otherwise only
 * files named INDEX.md (session start, which has to be fast).
 */
export function findOrphans(repo: Repo, { allMarkdown }: { allMarkdown: boolean }): string[] {
  const written = new Set<string>();
  for (const c of repo.collections) {
    if (c.indexFile !== undefined) written.add(c.indexFile);
    if (c.jsonFile !== undefined) written.add(c.jsonFile);
  }
  const candidates = listFiles(repo.root).filter((path) => {
    if (written.has(path)) return false;
    const name = relBasename(path);
    return (name === "index.json" || (allMarkdown ? /\.md$/i.test(name) : name === "INDEX.md")) && isFile(join(repo.root, path));
  });
  const status = repo.ignore.check(candidates.map((path) => ({ path, isDir: false })));
  return candidates.filter((path) => {
    const st = status.get(path) ?? {};
    return st.ignoredBy === undefined && !st.outside && isCardCatalogIndex(join(repo.root, path));
  });
}

export function isCardCatalogIndex(abs: string): boolean {
  let text: string;
  try {
    text = readFileSync(abs, "utf8");
  } catch {
    return false;
  }
  if (relBasename(abs) === "index.json") {
    try {
      const generatedBy = (JSON.parse(text) as { generatedBy?: unknown }).generatedBy;
      return generatedBy === "card-catalog" || generatedBy === "adr-index";
    } catch {
      return false;
    }
  }
  return text.split("\n", 5).some((line) => MARKERS.some((m) => line.startsWith(m)));
}

/** Paths git would show (tracked, or untracked and not ignored); every file outside git. Never enters nested repos. */
function listFiles(root: string): string[] {
  const git = spawnSync("git", ["ls-files", "-z", "--cached", "--others", "--exclude-standard"], { cwd: root, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
  if (git.status === 0) {
    return [...new Set(git.stdout.split("\0"))].filter((p) => p !== "" && !p.endsWith("/"));
  }
  // Outside git, the same bounds as finding default collections.
  const out: string[] = [];
  const walk = (dir: string, depth: number) => {
    if (depth > MAX_DEPTH) return;
    let entries;
    try {
      entries = readdirSync(join(root, dir), { withFileTypes: true });
    } catch {
      return;
    }
    if (dir !== "" && entries.some((e) => e.name === ".git")) return;
    for (const e of entries) {
      const path = joinRel(dir, e.name);
      if (e.isDirectory()) {
        if (!SKIP_DIRS.has(e.name) && !e.name.startsWith(".")) walk(path, depth + 1);
      } else if (e.isFile()) {
        out.push(path);
      }
    }
  };
  walk("", 0);
  return out.sort();
}
