import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { adr, type Files, makeRepo } from "./fixtures.ts";

const scripts = join(dirname(fileURLToPath(import.meta.url)), "..", "scripts");

function cli(root: string, ...args: string[]) {
  const r = spawnSync("node", [join(scripts, "cli.ts"), ...args], { cwd: root, encoding: "utf8" });
  return { code: r.status, out: r.stdout, err: r.stderr };
}

function json(root: string, ...args: string[]): unknown {
  return JSON.parse(cli(root, ...args, "--json").out);
}

const repoFiles: Files = {
  "card-catalog.json": {
    collections: [
      { dir: "src/*/docs/adr", type: "adr" },
      { dir: "docs/adr/archive", type: "adr", announce: false },
      { dir: "docs/postmortems", type: "postmortem", id: "{date}-{slug}", fields: { severity: "inline:Severity" } },
    ],
  },
  ".aiignore": "legacy/\n",
  "docs/adr/0001-a.md": adr("A", "First.", "status: accepted"),
  "docs/adr/archive/0001-old.md": adr("Old"),
  "docs/postmortems/2026-09-14-db.md": "# DB\n\nSeverity: high\n\nFailed over.\n",
  "docs/postmortems/notes.md": "# Notes\n",
  "legacy/docs/adr/0001-x.md": adr("X"),
  "old/INDEX.md": "# ADR index\n\nGenerated by the adr-index plugin from the ADRs in this directory.\n",
};

test("list shows collections, directories that aren't one, and orphans", () => {
  const root = makeRepo(repoFiles);
  const r = cli(root, "list");
  assert.equal(r.code, 0);
  assert.equal(
    r.out,
    [
      "docs/adr          adr         1 record   docs/adr/INDEX.md          missing",
      "docs/adr/archive  adr         1 record   docs/adr/archive/INDEX.md  missing, not announced",
      "docs/postmortems  postmortem  1 record   docs/postmortems/INDEX.md  missing",
      "legacy/docs/adr   adr         not indexed: ignored by .aiignore (default)",
      "src/*/docs/adr    adr         not indexed: matches no directory (config entry 1)",
      "orphaned index: old/INDEX.md",
      "",
    ].join("\n"),
  );
  const j = json(root, "list") as { config: string; collections: { dir: string; entry: number | null; state: string }[]; notIndexed: unknown[]; orphans: string[]; warnings: string[] };
  assert.equal(j.config, "card-catalog.json");
  assert.deepEqual(j.collections.map((c) => [c.dir, c.entry, c.state]), [["docs/adr", null, "missing"], ["docs/adr/archive", 2, "missing"], ["docs/postmortems", 3, "missing"]]);
  assert.deepEqual(j.notIndexed[0], { dir: "legacy/docs/adr", type: "adr", source: "default", entry: null, reason: "ignored", detail: ".aiignore" });
  assert.deepEqual(j.orphans, ["old/INDEX.md"]);
  assert.deepEqual(j.warnings, ['card-catalog.json: config entry 1: dir "src/*/docs/adr" matches no directory']);
});

test("reindex writes every collection, or the ones named, and reports unchanged ones", () => {
  const root = makeRepo(repoFiles);
  const named = cli(root, "reindex", "docs/postmortems");
  assert.equal(named.code, 0);
  assert.equal(named.out, "updated: docs/postmortems (1 postmortem)\n");
  assert.ok(existsSync(join(root, "docs/postmortems/INDEX.md")));
  assert.ok(!existsSync(join(root, "docs/adr/INDEX.md")));
  assert.equal(cli(root, "reindex").out, "updated: docs/adr (1 ADR)\nupdated: docs/adr/archive (1 ADR)\nunchanged: docs/postmortems (1 postmortem)\n");
  const notCollection = cli(root, "reindex", "legacy/docs/adr");
  assert.equal(notCollection.code, 1);
  assert.match(notCollection.err, /legacy\/docs\/adr is not a collection \(ignored by \.aiignore\)/);
});

test("the old reindex script is a shortcut for reindex --root", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A") });
  const r = spawnSync("node", [join(scripts, "reindex.ts"), root], { encoding: "utf8" });
  assert.equal(r.stdout, "updated: docs/adr (1 ADR)\n");
});

test("preview prints the index a profile would give, without writing, and refuses ignored directories", () => {
  const root = makeRepo({ ...repoFiles, "docs/runbooks/restart.md": "# Restart\n\nWhen stuck.\n" });
  const r = cli(root, "preview", "docs/runbooks", "--entry", '{"type":"runbook","guidance":"x"}');
  assert.equal(r.code, 0);
  assert.match(r.out, /^# Runbook index\n/);
  assert.match(r.out, /^- \[Runbook restart\]\(restart\.md\) \d{4}-\d{2}-\d{2} \| Restart \| When stuck\.$/m);
  assert.ok(!existsSync(join(root, "docs/runbooks/INDEX.md")));

  const skipped = cli(root, "preview", "docs/postmortems");
  assert.equal(skipped.err, "skipped: notes.md (name doesn't match id pattern {date}-{slug})\n");
  const j = json(root, "preview", "docs/postmortems") as { records: { label: string; line: string; fields: object }[]; skipped: unknown[] };
  assert.deepEqual(j.records.map((x) => [x.label, x.fields]), [["Postmortem 2026-09-14-db", { severity: "high" }]]);
  assert.match(j.records[0]?.line ?? "", /severity=high/);
  assert.deepEqual(j.skipped, [{ file: "notes.md", reason: "not-a-record" }]);

  const ignored = cli(root, "preview", "legacy/docs/adr");
  assert.equal(ignored.code, 1);
  assert.equal(ignored.out, "");
  assert.match(ignored.err, /ignored by \.aiignore/);
  assert.equal(cli(root, "preview", "docs/runbooks").code, 1, "a directory that isn't a collection needs --type or --entry");
});

test("profile shows where each value comes from", () => {
  const root = makeRepo(repoFiles);
  const r = cli(root, "profile", "docs/postmortems");
  assert.equal(r.code, 0);
  assert.match(r.out, /^docs\/postmortems: postmortem \(config entry 3\)$/m);
  assert.match(r.out, /^ {2}id +\{date\}-\{slug\} +config entry 3$/m);
  assert.match(r.out, /^ {2}title +frontmatter:title, heading +generic default$/m);
  const j = json(root, "profile", "docs/adr/archive") as { sources: Record<string, string>; settings: Record<string, unknown> };
  assert.equal(j.sources["label"], "built-in");
  assert.equal(j.settings["announce"], false);
});

test("validate reports problems with severities, fixes and exit codes", () => {
  const root = makeRepo({ ...repoFiles, "docs/adr/0002-b.md": adr("B", "Second.", "status: parked") });
  cli(root, "reindex");
  writeFileSync(join(root, "docs/adr/0003-c.md"), adr("C"));
  const r = cli(root, "validate");
  assert.equal(r.code, 1);
  assert.equal(
    r.out,
    [
      "error   stale-index      docs/adr/INDEX.md          out of date; run: card-catalog reindex docs/adr",
      "error   orphaned-index   old/INDEX.md               is a card-catalog index that no collection writes; delete the file, or make its directory a collection again",
      "warning config-no-match  card-catalog.json          config entry 1: dir \"src/*/docs/adr\" matches no directory",
      "warning unknown-status   docs/adr/0002-b.md         unrecognized status \"parked\"",
      "note    not-a-record     docs/postmortems/notes.md  name doesn't match id pattern {date}-{slug}",
      "5 problems (2 errors, 2 warnings, 1 note)",
      "",
    ].join("\n"),
  );
  const j = json(root, "validate") as { problems: { code: string; fix?: string }[]; counts: object };
  assert.deepEqual(j.counts, { error: 2, warning: 2, note: 1 });
  assert.equal(j.problems[0]?.fix, "card-catalog reindex docs/adr");

  const clean = makeRepo({ "docs/adr/0001-a.md": adr("A", "x", "status: parked") });
  cli(clean, "reindex");
  assert.equal(cli(clean, "validate").code, 0);
  assert.equal(cli(clean, "validate", "--strict").code, 1);
});

test("invalid config fails every command, and validate says why", () => {
  const root = makeRepo({ "card-catalog.json": "{ nope", "docs/adr/0001-a.md": adr("A") });
  const r = cli(root, "reindex");
  assert.equal(r.code, 1);
  assert.match(r.err, /card-catalog\.json is invalid/);
  assert.ok(!existsSync(join(root, "docs/adr/INDEX.md")));
  const v = cli(root, "validate");
  assert.equal(v.code, 1);
  assert.match(v.out, /^error +config-unreadable +card-catalog\.json +isn't valid JSON/m);
});

test("usage errors exit 2, and --version and --help work", () => {
  const root = makeRepo();
  assert.equal(cli(root, "frobnicate").code, 2);
  assert.equal(cli(root, "list", "--bogus").code, 2);
  assert.equal(cli(root, "list", "--strict").code, 2);
  assert.equal(cli(root, "preview").code, 2);
  const pkg = JSON.parse(readFileSync(join(scripts, "..", ".claude-plugin", "plugin.json"), "utf8")) as { version: string };
  assert.equal(cli(root, "--version").out, `${pkg.version}\n`);
  assert.match(cli(root, "--help").out, /^Usage: card-catalog <command>/m);
  assert.match(cli(root, "validate", "--help").out, /--strict/);
});

test("types lists the built-in record types", () => {
  const root = makeRepo();
  const r = cli(root, "types");
  assert.equal(r.code, 0);
  assert.equal(r.out, "adr  ADRs  architecture decisions\n");
  assert.deepEqual(json(root, "types"), {
    types: [{ name: "adr", plural: "ADRs", description: "architecture decisions" }],
    warnings: [],
  });
  assert.equal(cli(root, "types", "docs").code, 2);
});
