import assert from "node:assert/strict";
import { mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { contentHash, resolveAmendedAt } from "../scripts/core/amendments.ts";
import { buildIndex, writeIndex } from "../scripts/core/index-build.ts";
import { openRepo } from "../scripts/core/repo.ts";
import { adr, type Files, gitCommitAll, makeRepo } from "./fixtures.ts";

const T1 = new Date("2026-09-01T00:00:00.000Z");
const T2 = new Date("2026-09-10T00:00:00.000Z");

function build(root: string, dir = "docs/adr", now = T1) {
  const r = openRepo(root);
  assert.ok(r.ok);
  const c = r.repo.collections.find((x) => x.dir === dir);
  assert.ok(c, `no collection at ${dir}`);
  return { repo: r.repo, built: buildIndex(r.repo, c, { now }) };
}

function reindex(root: string, dir = "docs/adr", now = T1) {
  const { repo, built } = build(root, dir, now);
  return { changed: writeIndex(repo, built), built };
}

const read = (root: string, path: string) => readFileSync(join(root, path), "utf8");
const lines = (text: string) => text.split("\n").filter((l) => l.startsWith("- "));

test("an ADR collection's INDEX.md and index.json", () => {
  const root = makeRepo({
    "docs/adr/0001-rest.md": adr("REST over GraphQL", "We picked REST because clients are simple.", "status: superseded by ADR-0002"),
    "docs/adr/0002-graphql.md": adr("GraphQL gateway", "Mobile needs it.", "status: accepted\ndate: 2026-04-01\ntags: [api]\nrelates-to: ADR-0001"),
    "docs/adr/hub-0031-x.md": adr("Imported", "From hub.", "status: superseded by ADR-0042"),
    "docs/adr/hub-0042-y.md": adr("Imported two", "Also hub.", "status: accepted"),
    "docs/adr/README.md": "# About\n",
  });
  reindex(root);
  assert.equal(
    read(root, "docs/adr/INDEX.md"),
    [
      "# ADR index",
      "",
      "Generated by the card-catalog plugin from the ADRs in this directory. Edits here are overwritten.",
      "One line per ADR: `label [status] amended key=value … | title | summary`. Search it with grep, then open the ADRs that match.",
      "",
      "- [ADR-0001](0001-rest.md) [superseded by ADR-0002] 2026-09-01 | REST over GraphQL | We picked REST because clients are simple.",
      "- [ADR-0002](0002-graphql.md) [accepted] 2026-09-01 relates-to=ADR-0001 | GraphQL gateway | Mobile needs it.",
      "- [hub-0031](hub-0031-x.md) [superseded by hub-0042] 2026-09-01 | Imported | From hub.",
      "- [hub-0042](hub-0042-y.md) [accepted] 2026-09-01 | Imported two | Also hub.",
      "",
    ].join("\n"),
  );
  const json = read(root, "docs/adr/index.json").split("\n");
  assert.equal(json[0], '{"version":3,"generatedBy":"card-catalog","type":"adr","records":[');
  assert.equal(json.at(-2), "]}");
  const second = JSON.parse((json[2] ?? "").replace(/,$/, "")) as Record<string, unknown>;
  assert.deepEqual(Object.keys(second), ["id", "label", "slug", "title", "status", "summary", "file", "date", "tags", "links", "contentHash", "amendedAt"]);
  assert.deepEqual(second["links"], [{ type: "relates-to", target: "ADR-0001", file: "0001-rest.md" }]);
  const hub = JSON.parse((json[3] ?? "").replace(/,$/, "")) as Record<string, unknown>;
  assert.equal(hub["series"], "hub");
  assert.deepEqual(hub["links"], [{ type: "superseded-by", target: "hub-0042", file: "hub-0042-y.md" }]);
});

test("an index without key=value pairs keeps today's ADR header shape", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A") });
  reindex(root);
  assert.match(read(root, "docs/adr/INDEX.md"), /^One line per ADR: `label \[status\] amended \| title \| summary`\./m);
  assert.deepEqual(lines(read(root, "docs/adr/INDEX.md")), ["- [ADR-0001](0001-a.md) [unspecified] 2026-09-01 | A | A body."]);
});

test("writes are idempotent, and the state tracks the files on disk", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A") });
  assert.equal(build(root).built.state, "missing");
  assert.equal(reindex(root).changed, true);
  assert.equal(reindex(root, "docs/adr", T2).changed, false);
  assert.equal(build(root, "docs/adr", T2).built.state, "current");
  writeFileSync(join(root, "docs/adr/0002-b.md"), adr("B"));
  const stale = build(root, "docs/adr", T2).built;
  assert.equal(stale.state, "stale");
  assert.deepEqual(stale.problems.map((p) => `${p.code} ${p.path} ${p.fix ?? ""}`), ["stale-index docs/adr/INDEX.md card-catalog reindex docs/adr"]);
});

test("a collection with no records gets no index, and one that loses its last record keeps its header", () => {
  const root = makeRepo({ "docs/adr/README.md": "# About\n" });
  const empty = reindex(root);
  assert.equal(empty.built.state, "empty");
  assert.equal(empty.changed, false);
  assert.deepEqual(empty.built.problems.map((p) => p.code), ["empty-collection"]);

  writeFileSync(join(root, "docs/adr/0001-a.md"), adr("A"));
  reindex(root);
  rmSync(join(root, "docs/adr/0001-a.md"));
  assert.equal(reindex(root).changed, true);
  assert.deepEqual(lines(read(root, "docs/adr/INDEX.md")), []);
  assert.match(read(root, "docs/adr/index.json"), /"records":\[\n\n\]\}\n$/);
});

test("amendedAt survives rebuilds and moves only when the content does", () => {
  assert.equal(contentHash("# A\n\nBody.\n"), contentHash("# A  \r\n\r\nBody.\r\n\n"));
  assert.notEqual(contentHash("# A\n\nBody.\n"), contentHash("# A\n\nBody!\n"));
  assert.equal(resolveAmendedAt("abc", undefined, () => "2026-01-01T00:00:00.000Z", T2), "2026-01-01T00:00:00.000Z");

  const root = makeRepo({ "docs/adr/0001-a.md": adr("A", "First.") });
  reindex(root, "docs/adr", T1);
  assert.equal(build(root, "docs/adr", T2).built.records[0]?.amendedAt, T1.toISOString());
  writeFileSync(join(root, "docs/adr/0001-a.md"), adr("A", "First, amended."));
  assert.equal(build(root, "docs/adr", T2).built.records[0]?.amendedAt, T2.toISOString());
});

test("an unparseable edit keeps the previous line but records the amendment", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A", "First.") });
  reindex(root, "docs/adr", T1);
  writeFileSync(join(root, "docs/adr/0001-a.md"), "no heading any more");
  const { built } = build(root, "docs/adr", T2);
  assert.equal(built.records[0]?.title, "A");
  assert.equal(built.records[0].amendedAt, T2.toISOString());
  assert.deepEqual(built.problems.map((p) => p.code), ["no-title", "stale-index"]);
});

test("a backfill uses each record's last commit date, and now for uncommitted files", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A"), "docs/adr/0002-b.md": adr("B"), "docs/adr/0004-café.md": adr("Café") }, { git: true });
  gitCommitAll(root, "2026-03-01T12:00:00+02:00");
  writeFileSync(join(root, "docs/adr/0002-b.md"), adr("B", "Revised."));
  gitCommitAll(root, "2026-04-01T12:00:00Z");
  writeFileSync(join(root, "docs/adr/0003-c.md"), adr("C"));
  assert.deepEqual(
    build(root, "docs/adr", T2).built.records.map((r) => r.amendedAt),
    ["2026-03-01T10:00:00.000Z", "2026-04-01T12:00:00.000Z", T2.toISOString(), "2026-03-01T10:00:00.000Z"],
  );
});

test("a version 2 index is read for its hashes, counts as current, and is rewritten as version 3", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A") });
  const hash = contentHash(adr("A"));
  writeFileSync(
    join(root, "docs/adr/index.json"),
    `{"version":2,"generatedBy":"card-catalog","adrs":[\n{"id":1,"slug":"a","title":"Old","status":"accepted","summary":"x","file":"0001-a.md","contentHash":"${hash}","amendedAt":"2026-01-01T00:00:00.000Z"}\n]}\n`,
  );
  const first = build(root, "docs/adr", T2).built;
  assert.equal(first.records[0]?.amendedAt, "2026-01-01T00:00:00.000Z");
  writeFileSync(join(root, "docs/adr/INDEX.md"), first.indexMd ?? "");
  assert.equal(build(root, "docs/adr", T2).built.state, "current");
  reindex(root, "docs/adr", T2);
  assert.match(read(root, "docs/adr/index.json"), /^\{"version":3,/);
});

test("an index.json from a newer card-catalog is never overwritten", () => {
  const root = makeRepo({ "docs/adr/0001-a.md": adr("A"), "docs/adr/index.json": '{"version":4,"generatedBy":"card-catalog","records":[]}\n' });
  const { changed, built } = reindex(root);
  assert.equal(changed, false);
  assert.ok(built.problems.some((p) => p.code === "newer-index"));
  assert.equal(read(root, "docs/adr/index.json"), '{"version":4,"generatedBy":"card-catalog","records":[]}\n');
});

const postmortems: Files = {
  "card-catalog.json": {
    collections: [{
      dir: "docs/postmortems", type: "postmortem", id: "{date}-{slug}", indexPath: "../postmortems.md",
      fields: { severity: "inline:Severity" }, links: { follows: "frontmatter:follows" },
    }],
  },
  "docs/postmortems/2026-09-14-db-outage.md": "---\nfollows: ADR-0001\n---\n# DB | outage\n\nSeverity: high\n\nThe primary failed | over.\n",
  "docs/postmortems/2026-09-20-dns.md": "---\nfollows: Postmortem 2026-09-14-db-outage\n---\n# DNS\n\nResolver timeouts.\n",
  "docs/postmortems/notes.md": "# Notes\n",
  "docs/adr/0001-a.md": adr("A"),
};

test("a user-defined type: no status, fields and links as pairs, an index outside its directory", () => {
  const root = makeRepo(postmortems);
  const { built } = reindex(root, "docs/postmortems");
  assert.equal(
    read(root, "docs/postmortems.md"),
    [
      "# Postmortem index",
      "",
      "Generated by the card-catalog plugin from the postmortems in `postmortems`. Edits here are overwritten.",
      "One line per postmortem: `label amended key=value … | title | summary`. Search it with grep, then open the postmortems that match.",
      "",
      "- [Postmortem 2026-09-14-db-outage](postmortems/2026-09-14-db-outage.md) 2026-09-01 severity=high follows=ADR-0001 | DB \\| outage | The primary failed \\| over.",
      '- [Postmortem 2026-09-20-dns](postmortems/2026-09-20-dns.md) 2026-09-01 follows="Postmortem 2026-09-14-db-outage" | DNS | Resolver timeouts.',
      "",
    ].join("\n"),
  );
  assert.match(read(root, "docs/postmortems/index.json"), /"type":"postmortem"/);
  assert.deepEqual(built.skipped, [{ file: "notes.md", reason: "not-a-record", message: "name doesn't match id pattern {date}-{slug}" }]);
  assert.deepEqual(
    built.records.map((r) => r.links),
    [[{ type: "follows", target: "ADR-0001", file: "../adr/0001-a.md" }], [{ type: "follows", target: "Postmortem 2026-09-14-db-outage", file: "2026-09-14-db-outage.md" }]],
  );
});

test("links resolve in their own collection first, then across the repo", () => {
  const root = makeRepo({
    "docs/adr/0001-a.md": adr("A", "Body.", "relates-to: [ADR-0002, ADR-0009, Some free text]"),
    "docs/adr/0002-b.md": adr("B"),
    "svc/one/docs/adr/0009-x.md": adr("X"),
    "svc/two/docs/adr/0009-y.md": adr("Y"),
    "svc/one/docs/adr/0003-c.md": adr("C", "Body.", "supersedes: [ADR-0001](../../../../docs/adr/0001-a.md)\nrelates-to: [gone](0099-gone.md)"),
  });
  const own = build(root).built;
  assert.deepEqual(own.records[0]?.links, [
    { type: "relates-to", target: "ADR-0002", file: "0002-b.md" },
    { type: "relates-to", target: "ADR-0009" },
    { type: "relates-to", target: "Some free text" },
  ]);
  assert.deepEqual(own.problems.map((p) => p.code), ["ambiguous-link", "missing-index"]);
  const other = build(root, "svc/one/docs/adr").built;
  assert.deepEqual(other.records[0]?.links, [
    { type: "supersedes", target: "ADR-0001", file: "../../../../docs/adr/0001-a.md" },
    { type: "relates-to", target: "gone", file: "0099-gone.md" },
  ]);
  assert.deepEqual(other.problems.map((p) => p.code), ["broken-link", "missing-index"]);
});

test("ignored files and nested collections' files are not records", () => {
  const root = makeRepo({
    ".aiignore": "docs/notes/private-*.md\n",
    "docs/notes/a.md": adr("A"),
    "docs/notes/private-b.md": adr("B"),
    "docs/notes/sub/c.md": adr("C"),
    "docs/notes/adr-dir/docs/adr/0001-x.md": adr("X"),
    "card-catalog.json": { collections: [{ dir: "docs/notes", type: "note", match: "**/*.md" }, { dir: "docs/notes/sub", type: "other" }] },
  });
  assert.deepEqual(build(root, "docs/notes").built.records.map((r) => r.file), ["a.md"]);
});

test("git's ignore rules still apply to records reached through a symlinked directory", () => {
  const root = makeRepo({ ".gitignore": "0002-secret.md\n", "shared/adr/0001-a.md": adr("A"), "shared/adr/0002-secret.md": adr("Secret") }, { git: true });
  mkdirSync(join(root, "svc/docs"), { recursive: true });
  symlinkSync(join(root, "shared/adr"), join(root, "svc/docs/adr"));
  assert.deepEqual(build(root, "svc/docs/adr").built.records.map((r) => r.file), ["0001-a.md"]);
});
