// Renders <adr-dir>/INDEX.md: one line per ADR, for agents to grep.
//
// One line per record is the point. A grep hit on a keyword returns the whole
// record (ID, status, title, summary), where a multi-line format would return
// a fragment with no ADR attached to it.

import type { IndexedAdr } from "./index-store.ts";

export const INDEX_MD_FILE = "INDEX.md";

export function renderIndexMd(adrs: IndexedAdr[]): string {
  const lines = [
    "# ADR index",
    "",
    "Generated by the adr-index plugin from the ADRs in this directory. Edits here are overwritten.",
    "One line per ADR: `ID [status] amended | title | summary`. Search it with grep, then open the ADRs that match.",
    "",
    ...adrs.map(
      (adr) => `- ${ref(adr.id, adr.prefix)} [${status(adr)}] ${adr.amendedAt.slice(0, 10)} | ${adr.title} | ${adr.summary}`,
    ),
  ];
  return lines.join("\n") + "\n";
}

function status(adr: IndexedAdr): string {
  return adr.status === "superseded" && adr.supersededBy !== undefined
    ? `superseded by ${ref(adr.supersededBy, adr.supersededByPrefix)}`
    : adr.status;
}

/** ADR-0007 for the main sequence, hub-0007 for a prefixed series. */
export function ref(id: number, prefix: string | undefined): string {
  return `${prefix ?? "ADR"}-${String(id).padStart(4, "0")}`;
}
